import 'package:drift/drift.dart';
import 'tables/expense_item_table.dart';
import 'tables/income_stream_model_table.dart';
import 'tables/categories_table.dart';
import 'tables/app_meta_table.dart';
import 'tables/single_event_table.dart';
import 'tables/period_snapshot_table.dart';
import 'tables/synced_task_table.dart';
import 'tables/manual_account_table.dart';
import 'tables/linked_account_table.dart';
import 'tables/balance_history_table.dart';
import '../../navigation_items/single_events/single_event_model.dart';
import 'daos/expenses_dao.dart';
// These two are used by the tables above (intEnum<FrequencyUnit>(),
// Constant(otherCategory)/Constant(creditCardsCategory)) but not otherwise
// referenced directly in this file. They still need to be imported here,
// though, not just in the table files: `part 'app_database.g.dart'` below
// shares *this* file's import scope, and the generated code in that part
// file references FrequencyUnit/otherCategory/creditCardsCategory by name.
// Dart imports aren't transitive -- importing expenses_table.dart doesn't
// also give this file whatever expenses_table.dart itself imported.
import '../../utils/frequency_unit.dart';
import '../../utils/category_manager.dart';
import '../../navigation_items/expense_activity/funding_source.dart';
import 'app_database.steps.dart';

part 'app_database.g.dart'; // generated by `dart run build_runner build`

@DriftDatabase(
  tables: [ExpenseItemRows, IncomeStreamModelRows, CategoryRows, AppMetaRows, SingleEventRows,
      PeriodSnapshotRows, SyncedTaskRows, ManualAccountRows, LinkedItemRows, LinkedAccountRows,
      BalanceHistoryRows],
  daos: [ExpensesDao],
)
class AppDatabase extends _$AppDatabase {
  AppDatabase(super.executor);

  // Version 1 is the schema the app first ships with (snapshot in
  // drift_schemas/app_database/drift_schema_v1.json). Every change after it gets a
  // new version and a migration step, so updates keep users' data:
  //   1. change the tables and bump schemaVersion;
  //   2. run `dart run drift_dev make-migrations` (snapshots the new version and
  //      generates app_database.steps.dart plus migration tests in test/drift/);
  //   3. add the step to onUpgrade below (e.g. `from1To2: (m, schema) async =>
  //      m.addColumn(schema.expenseItemRows, schema.expenseItemRows.note)`);
  //   4. run `dart run drift_dev schema generate --data-classes --companions
  //      drift_schemas/app_database/ test/drift/app_database/generated/` and the tests.
  // test/drift/app_database/schema_test.dart fails if step 1 happens without the rest.
  //
  // Versions: 1, the first; 2, Settings > Appearance (theme mode and accent color);
  // 3, Apple Reminders as a task sync service; 4, balance history (Visuals > Net Balance).
  @override
  int get schemaVersion => 4;

  @override
  MigrationStrategy get migration => MigrationStrategy(
        onCreate: (m) => m.createAll(),
        onUpgrade: stepByStep(
          from1To2: (m, schema) async {
            await m.addColumn(schema.appMetaRows, schema.appMetaRows.themeMode);
            await m.addColumn(schema.appMetaRows, schema.appMetaRows.accentColor);
            await m.addColumn(schema.appMetaRows, schema.appMetaRows.customAccent);
          },
          from2To3: (m, schema) async {
            await m.addColumn(schema.appMetaRows, schema.appMetaRows.tasksProvider);
          },
          from3To4: (m, schema) async {
            await m.createTable(schema.balanceHistoryRows);
          },
        ),
      );
}
