import 'package:drift/drift.dart';
import 'tables/expense_item_table.dart';
import 'tables/income_stream_model_table.dart';
import 'tables/categories_table.dart';
import 'tables/app_meta_table.dart';
import 'tables/single_event_table.dart';
import '../../navigation_items/single_events/single_event_model.dart';
import 'daos/expenses_dao.dart';
// These two are used by the tables above (intEnum<FrequencyUnit>(),
// Constant(otherCategory)/Constant(creditCardsCategory)) but not otherwise
// referenced directly in this file. They still need to be imported here,
// though, not just in the table files: `part 'app_database.g.dart'` below
// shares *this* file's import scope, and the generated code in that part
// file references FrequencyUnit/otherCategory/creditCardsCategory by name.
// Dart imports aren't transitive -- importing expenses_table.dart doesn't
// also give this file whatever expenses_table.dart itself imported.
import '../../utils/frequency_unit.dart';
import '../../utils/category_manager.dart';

part 'app_database.g.dart'; // generated by `dart run build_runner build`

@DriftDatabase(
  tables: [ExpenseItemRows, IncomeStreamModelRows, CategoryRows, AppMetaRows, SingleEventRows],
  daos: [ExpensesDao],
)
class AppDatabase extends _$AppDatabase {
  AppDatabase(super.executor);

  @override
  int get schemaVersion => 1;

  // No migration strategy needed yet -- this is a brand-new database with
  // no predecessor (the old AES-GCM file format isn't being migrated).
  // Add a MigrationStrategy + bump schemaVersion the first time this
  // schema changes after it's actually shipped/used anywhere.
}
